export default{
    path:"/home",
    component:_=>import("@pages/home"),
    name:"home",
    meta:{
        requireAuth:true
    },
    children:[
        {
            path:"/home",
            redirect: "/home/shouye"
        },
        {
            path:"addwoman",
            component:_=>import("@components/addwoman"),
            name:"addwoman",
        },
        {
            path:"bijilist",
            component:_=>import("@components/bijilist"),
            name:"bijilist",
            children:[
                {
                    path:"./detail",
                    component:_=>import("@components/detail")
                }
            ]
        },
        {
            path:"pushbiji",
            component:_=>import("@components/pushbiji"),
            name:"pushbiji",
        },
        {
            path:"shouye",
            component:_=>import("@components/shouye"),
            name:"shouye",
        },
        {
            path:"usercenter",
            component:_=>import("@components/usercenter"),
            name:"usercenter",
        },
        {
            path:"womanlist",
            component:_=>import("@components/womanlist"),
            name:"womanlist",
        },
    ]
}